title:            research blog
description:      Research blog of Marat I. Latypov (Georgia Tech Lorraine) - posts on Dream.3D, ABAQUS, MTEX, Python, MATLAB - micromechanics of materials, microstructures, crystal plasticity, texture, materials informatics
disqus_shortname: latmarat
reading_time:     true
words_per_minute: 200
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url: /hpstr-trial

# Owner/author information
owner:
  name:           Marat I. Latypov
  avatar:         avatar.jpg
  bio:            "Materials Scientist at Georgia Tech Lorraine."
  email:          marat.latypov@georgiatech-metz.fr
  # Social networking links used in footer. Update and remove as you like.
  twitter:
  facebook:
  github: #https://github.com/latmarat
  stackexchange:
  linkedin: latmarat
  instagram:
  flickr:
  tumblr:
  # google plus id, include the '+', eg +mmistakes
  google_plus:
  researchgate: Marat_Latypov
  google_scholar: We5aJywAAAAJ&hl=en&oi=ao

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-61278008-2
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Paris
future:      true
highlighter: rouge
markdown:    kramdown
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
