title:            research blog
description:      Research blog of Marat I. Latypov (Georgia Tech Lorraine) - posts on Dream.3D, ABAQUS, MTEX, Python, MATLAB - micromechanics of materials, microstructures, crystal plasticity, texture, materials informatics
disqus_shortname: latmarat
reading_time:     true
words_per_minute: 200
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url: /blog

# Owner/author information
owner:
  name:           Marat I. Latypov
  avatar:         avatar.jpg
  bio:            "Materials Scientist at Georgia Tech Lorraine."
  email:          marat.latypov@georgiatech-metz.fr
  # Social networking links used in footer. Update and remove as you like.
  twitter:
  facebook:
  github: #https://github.com/latmarat
  stackexchange:
  linkedin: latmarat
  instagram:
  flickr:
  tumblr:
  # google plus id, include the '+', eg +mmistakes
  google_plus:
  researchgate: Marat_Latypov
  google_scholar: We5aJywAAAAJ&hl=en&oi=ao

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-61278008-2
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Paris
future:      true
highlighter: rouge
markdown:    kramdown
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
